### ISSUE TITLE
[enhancement] Webhook optimization

### ISSUE THREAD

**Issue by sadadw1** [XiaoMi/ozhera#213]
- [ ] Webhook supports pod filtering #211 
- [ ] Move the creation of webhook-config to ozhera-operator #210 
- [ ] Webhook supports automatic injection of the log-agent container and environment variables #212
